[package]
name = "curther"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic_float = "1.1.0"
clap = { version = "4.5.58", features = ["derive"] }
crossbeam-channel = "0.5.15"
mouse_position = "0.1.4"
rodio = "0.21.1"
log = "0.4.29"
rdev = "0.5.3"
